name: my_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  path_provider: ^2.1.1
  path: ^1.8.3
  geocoding: ^2.1.0
  image_picker: ^1.0.4
  # Commented out Google Maps since you're switching to OpenStreetMap
  # google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  permission_handler: ^11.0.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/pothole1.jpg
    - assets/pothole2.jpg
    - assets/pothole3.jpg
    - assets/pothole4.jpg
    - assets/deepak.jpeg
